name: audio-latent-composition
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit==11.1
  - pytorch<=1.7.1
  - cudnn
  - torchvision<=0.3.0
  - torchaudio
  - numpy
  - scipy
  - ipython
  - matplotlib
  - pandas
  - jupyter
  - pip
  - tensorboard
  - tqdm
  - pillow
  - opencv
  - sk-video
  - dlib
  - scikit-image
  - asn1crypto>=0.24.0
  - audioread>=2.1.8
  - certifi>=2019.9.11
  - cffi>=1.11.5
  - chardet>=3.0.4
  - conda>=4.7.12
  - conda-package-handling>=1.6.0
  - cryptography>=2.4.2
  - decorator>=4.4.2
  - dill>=0.3.1.1
  - idna>=2.8
  - joblib>=0.14.1
  - librosa==0.7.2
  - numba==0.52.0
  - pycosat>=0.6.3
  - pycparser>=2.19
  - pyOpenSSL>=18.0.0
  - PySocks>=1.6.8
  - requests>=2.21.0
  - resampy>=0.2.2
  - ruamel.yaml
  - scikit-learn>=0.22.2.post1
  - six>=1.12.0
  - pysoundfile
  - tqdm>=4.38.0
  - urllib3>=1.24.2
  - pyFFTW 
  - mido
  - pip:
     - oyaml
     - lpips
     - prdc
     - ninja
     - ipywidgets
     - gdown
     - streamlit
     - cython
     - tifresi
